---
- name: ensure /data/bridge_reachability exists
  file: >
    path=/data/bridge_reachability
    owner="{{ ooni_user }}"
    group="{{ ooni_user }}"
    state="directory"
    mode=0644
  sudo: yes

- name: ensure ~/.ooni/ exists
  file: >
    path={{ ooni_home }}/.ooni
    owner="{{ ooni_user }}"
    group="{{ ooni_user }}"
    state="directory"
    mode=0644

- name: ensure templated ooniprobe.conf is installed
  template: >
    src=ooniprobe.conf
    dest="{{ ooni_home }}/.ooni/ooniprobe.conf"
    owner="{{ ooni_user }}"
    group="{{ ooni_user }}"
    mode=0644

- name: write list of bridges to test
  copy: >
    src=bridges.txt
    dest=/data/bridge_reachability/bridges.txt
    owner="{{ ooni_user }}"
    group="{{ ooni_user }}"
    mode=0644

- name: write run.sh script for bridge_reachability test
  template: >
    src="bridge_reachability_run.sh"
    dest="/data/bridge_reachability/run.sh"
    owner="{{ ooni_user }}"
    group="{{ ooni_user }}"
    mode=0644

- name: get the hour as local time relative to midnight GMT
  shell: 'date "+%H" -d "00:00:00 -0000"'
  register: hour

- name: get the minute as local time relative to midnight GMT
  shell: 'date "+%M" -d "00:00:00 -0000"'
  register: minute

- cron: >
    name="bridge_reachability"
    user="{{ ooni_user }}"
    minute="{{ minute.stdout }}"
    hour="{{ hour.stdout }}"
    job="/data/bridge_reachability/run.sh"
  when: ooni_cron_bridge_reachability == True
