---

- name: ensure backports apt repo is setup
  apt_repository: >
    repo="deb {{ backports_url }} {{ backports_distribution_release }} main"
    state=present 
    update_cache=yes
  sudo: yes

- name: ensure ooniprobe from backports is installed
  apt: >
    pkg=ooniprobe
    default_release="{{ backports_distribution_release }}"
    state=present
  sudo: yes
