---
- hosts: ooni-planetlab
  roles:
    - { role: ansible-ooniprobe,
        ooni_planetlab_deploy: true,
        ooni_user: "uwaterloo_geossl",
        ooni_home: "/home/uwaterloo_geossl",
        ooni_start_tor: "false",
        sudo: no
      }
